/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FornecedorIdRouteImport } from './routes/fornecedor.$id'
import { Route as FornecedorIdIndexRouteImport } from './routes/fornecedor.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorIdRoute = FornecedorIdRouteImport.update({
  id: '/fornecedor/$id',
  path: '/fornecedor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorIdIndexRoute = FornecedorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FornecedorIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fornecedor/$id': typeof FornecedorIdRouteWithChildren
  '/fornecedor/$id/': typeof FornecedorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fornecedor/$id': typeof FornecedorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fornecedor/$id': typeof FornecedorIdRouteWithChildren
  '/fornecedor/$id/': typeof FornecedorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fornecedor/$id' | '/fornecedor/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fornecedor/$id'
  id: '__root__' | '/' | '/fornecedor/$id' | '/fornecedor/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FornecedorIdRoute: typeof FornecedorIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/$id': {
      id: '/fornecedor/$id'
      path: '/fornecedor/$id'
      fullPath: '/fornecedor/$id'
      preLoaderRoute: typeof FornecedorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/$id/': {
      id: '/fornecedor/$id/'
      path: '/'
      fullPath: '/fornecedor/$id/'
      preLoaderRoute: typeof FornecedorIdIndexRouteImport
      parentRoute: typeof FornecedorIdRoute
    }
  }
}

interface FornecedorIdRouteChildren {
  FornecedorIdIndexRoute: typeof FornecedorIdIndexRoute
}

const FornecedorIdRouteChildren: FornecedorIdRouteChildren = {
  FornecedorIdIndexRoute: FornecedorIdIndexRoute,
}

const FornecedorIdRouteWithChildren = FornecedorIdRoute._addFileChildren(
  FornecedorIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FornecedorIdRoute: FornecedorIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
