/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FornecedorIdRouteImport } from './routes/fornecedor.$id'
import { Route as FornecedorIdIndexRouteImport } from './routes/fornecedor.$id.index'
import { Route as FornecedorIdObservacoesRouteImport } from './routes/fornecedor.$id.observacoes'
import { Route as FornecedorIdPrediosRouteImport } from './routes/fornecedor.$id.predios'
import { Route as FornecedorIdTransferenciasRouteImport } from './routes/fornecedor.$id.transferencias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorIdRoute = FornecedorIdRouteImport.update({
  id: '/fornecedor/$id',
  path: '/fornecedor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorIdIndexRoute = FornecedorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FornecedorIdRoute,
} as any)
const FornecedorIdObservacoesRoute = FornecedorIdObservacoesRouteImport.update({
  id: '/observacoes',
  path: '/observacoes',
  getParentRoute: () => FornecedorIdRoute,
} as any)
const FornecedorIdPrediosRoute = FornecedorIdPrediosRouteImport.update({
  id: '/predios',
  path: '/predios',
  getParentRoute: () => FornecedorIdRoute,
} as any)
const FornecedorIdTransferenciasRoute =
  FornecedorIdTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => FornecedorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fornecedor/$id': typeof FornecedorIdRouteWithChildren
  '/fornecedor/$id/observacoes': typeof FornecedorIdObservacoesRoute
  '/fornecedor/$id/predios': typeof FornecedorIdPrediosRoute
  '/fornecedor/$id/transferencias': typeof FornecedorIdTransferenciasRoute
  '/fornecedor/$id/': typeof FornecedorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fornecedor/$id/observacoes': typeof FornecedorIdObservacoesRoute
  '/fornecedor/$id/predios': typeof FornecedorIdPrediosRoute
  '/fornecedor/$id/transferencias': typeof FornecedorIdTransferenciasRoute
  '/fornecedor/$id': typeof FornecedorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fornecedor/$id': typeof FornecedorIdRouteWithChildren
  '/fornecedor/$id/observacoes': typeof FornecedorIdObservacoesRoute
  '/fornecedor/$id/predios': typeof FornecedorIdPrediosRoute
  '/fornecedor/$id/transferencias': typeof FornecedorIdTransferenciasRoute
  '/fornecedor/$id/': typeof FornecedorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fornecedor/$id'
    | '/fornecedor/$id/observacoes'
    | '/fornecedor/$id/predios'
    | '/fornecedor/$id/transferencias'
    | '/fornecedor/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fornecedor/$id/observacoes'
    | '/fornecedor/$id/predios'
    | '/fornecedor/$id/transferencias'
    | '/fornecedor/$id'
  id:
    | '__root__'
    | '/'
    | '/fornecedor/$id'
    | '/fornecedor/$id/observacoes'
    | '/fornecedor/$id/predios'
    | '/fornecedor/$id/transferencias'
    | '/fornecedor/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FornecedorIdRoute: typeof FornecedorIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/$id': {
      id: '/fornecedor/$id'
      path: '/fornecedor/$id'
      fullPath: '/fornecedor/$id'
      preLoaderRoute: typeof FornecedorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/$id/': {
      id: '/fornecedor/$id/'
      path: '/'
      fullPath: '/fornecedor/$id/'
      preLoaderRoute: typeof FornecedorIdIndexRouteImport
      parentRoute: typeof FornecedorIdRoute
    }
    '/fornecedor/$id/observacoes': {
      id: '/fornecedor/$id/observacoes'
      path: '/observacoes'
      fullPath: '/fornecedor/$id/observacoes'
      preLoaderRoute: typeof FornecedorIdObservacoesRouteImport
      parentRoute: typeof FornecedorIdRoute
    }
    '/fornecedor/$id/predios': {
      id: '/fornecedor/$id/predios'
      path: '/predios'
      fullPath: '/fornecedor/$id/predios'
      preLoaderRoute: typeof FornecedorIdPrediosRouteImport
      parentRoute: typeof FornecedorIdRoute
    }
    '/fornecedor/$id/transferencias': {
      id: '/fornecedor/$id/transferencias'
      path: '/transferencias'
      fullPath: '/fornecedor/$id/transferencias'
      preLoaderRoute: typeof FornecedorIdTransferenciasRouteImport
      parentRoute: typeof FornecedorIdRoute
    }
  }
}

interface FornecedorIdRouteChildren {
  FornecedorIdObservacoesRoute: typeof FornecedorIdObservacoesRoute
  FornecedorIdPrediosRoute: typeof FornecedorIdPrediosRoute
  FornecedorIdTransferenciasRoute: typeof FornecedorIdTransferenciasRoute
  FornecedorIdIndexRoute: typeof FornecedorIdIndexRoute
}

const FornecedorIdRouteChildren: FornecedorIdRouteChildren = {
  FornecedorIdObservacoesRoute: FornecedorIdObservacoesRoute,
  FornecedorIdPrediosRoute: FornecedorIdPrediosRoute,
  FornecedorIdTransferenciasRoute: FornecedorIdTransferenciasRoute,
  FornecedorIdIndexRoute: FornecedorIdIndexRoute,
}

const FornecedorIdRouteWithChildren = FornecedorIdRoute._addFileChildren(
  FornecedorIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FornecedorIdRoute: FornecedorIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
